---
meae-id: meae.congressional.congress03.ky.county
type: congressional
level: state
state: Kentucky
geography: county
congressnum: 3
congressordinal: 3rd
title: '3rd Congress: Kentucky 1792'
year: 1792
legend: fed-vs-rep
nnv:
- id: ky.uscongresssoutherndistrict.1792
  name: KY US Congress 1792 District 1
- id: ky.uscongressnortherndistrict.1792
  name: KY US Congress 1792 District 2
related-maps:
- id: meae.congressional.congress04.ky.county
  name: KY 4th Congress
  type: next
# - id: meae.congressional.congress03.national.district
#   name: National 3rd Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress03.ky.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data("1792-06-01") %>%
  map_counties(state = "Kentucky", height = "400px")
```

</div>

Kentucky elected two Democratic-Republicans to the Third Congress.

Mapping this election is not possible because no returns survive at the county or district levels.

Kentucky used a district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
