---
meae-id: meae.congressional.congress05.ma.county
type: congressional
level: state
state: Massachusetts
geography: county
congressnum: 5
congressordinal: 5th
title: '5th Congress: Massachusetts 1796'
year: 1796
legend: fed-vs-anti
nnv:
- id: ma.uscongress.western.1.1796
  name: MA US Congress 1796 District 1
- id: ma.uscongress.western.2.ballot2.1797
  name: MA US Congress 1797 District 2
- id: ma.uscongress.western.3.1796
  name: MA US Congress 1796 District 3
- id: ma.uscongress.western.4.1796
  name: MA US Congress 1796 District 4
- id: ma.uscongress.southern.1.1796
  name: MA US Congress 1796 District 5
- id: ma.uscongress.southern.2.1796
  name: MA US Congress 1796 District 6
- id: ma.uscongress.southern.3.ballot3.1797
  name: MA US Congress 1797 District 7
- id: ma.uscongress.middle.1.1796
  name: MA US Congress 1796 District 8
- id: ma.uscongress.middle.2.1796
  name: MA US Congress 1796 District 9
- id: ma.uscongress.middle.3.1796
  name: MA US Congress 1796 District 10
- id: ma.uscongress.middle.4.1796
  name: MA US Congress 1796 District 11
- id: ma.uscongress.eastern.1.ballot3.1797
  name: MA US Congress 1797 District 12
- id: ma.uscongress.eastern.2.1796
  name: MA US Congress 1796 District 13
- id: ma.uscongress.eastern.3.1796
  name: MA US Congress 1796 District 14
related-maps:
- id: meae.congressional.congress04.ma.county
  name: MA 4th Congress
  type: previous
# - id: meae.congressional.congress06.ma.county
#   name: MA 6th Congress
#   type: next
# - id: meae.congressional.congress05.national.district
#   name: National 5th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress05.ma.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  map_counties() %>% 
  fitBounds(-73.508, 41.186, -69.861, 43.75)
```

</div>

Massachusetts elected six Federalists and eight members who had no official party affiliation to the Fifth Congress.

Massachusetts used the district system for electing members to Congress.

In 1797 Massachusett held a [special election](https://elections.lib.tufts.edu/catalog/tufts:ma.uscongress.middle.4.special.1797) in which Bailey Bartlett was elected to replace Theophilus Bradley, who resigned from office.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
