---
meae-id: meae.congressional.congress04.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 4
congressordinal: 4th
title: '4th Congress: Tennessee 1796'
year: 1796
legend: fed-vs-rep
nnv:
- id: tn.uscongress.1796
  name: TN US Congress 1796 At Large
related-maps:
- id: meae.congressional.congress05.tn.county
  name: TN 5th Congress
  type: next
# - id: meae.congressional.congress04.national.district
#   name: National 4th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress04.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data(election_date = "1796-11-01") %>%
      filter(id != "tns_nca1",
             id != "tns_nca1") %>% 
  map_counties(congress = 4, height = "300px")
```

</div>

In its first congressional election, Tennessee elected one Democratic-Republican to the Fourth Congress. Andrew Jackson was seated for the second session of that Congress.

Tennessee used a statewide at-large system for electing its members to Congress. Votes were reported within administrative districts that contained several counties.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
