---
meae-id: meae.congressional.congress14.nc.county
type: congressional
level: state
state: North Carolina
geography: county
congressnum: 14
congressordinal: 14th
title: '14th Congress: North Carolina 1815'
year: 1815
legend: fed-vs-rep
nnv:
- id: nc.uscongress1.1815
  name: NC US Congress 1815 District 1
- id: nc.uscongress2.1815
  name: NC US Congress 1815 District 2
- id: nc.uscongress3.1815
  name: NC US Congress 1815 District 3
- id: nc.uscongress4.1815
  name: NC US Congress 1815 District 4
- id: nc.uscongress5.1815
  name: NC US Congress 1815 District 5
- id: nc.uscongress6.1815
  name: NC US Congress 1815 District 6
- id: nc.uscongress7.1815
  name: NC US Congress 1815 District 7
- id: nc.uscongress8.1815
  name: NC US Congress 1815 District 8
- id: nc.uscongress9.1815
  name: NC US Congress 1815 District 9
- id: nc.uscongress10.1815
  name: NC US Congress 1815 District 10
- id: nc.uscongress11.1815
  name: NC US Congress 1815 District 11
- id: nc.uscongress12.1815
  name: NC US Congress 1815 District 12
- id: nc.uscongress13.1815
  name: NC US Congress 1815 District 13
related-maps:
- id: meae.congressional.congress13.nc.county
  name: NC 13th Congress
  type: previous
- id: meae.congressional.congress15.nc.county
  name: NC 15th Congress
  type: next
#- id: meae.congressional.congress14.national.district
#  name: National 14th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress14.nc.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", congress = 14)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
