---
meae-id: meae.congressional.congress09.national.county
type: congressional
level: national
geography: county
congressnum: 9
congressordinal: 9th
title: '9th Congress: National, 1804-1805'
year: 1804
legend: 'dissrep'
related-maps:
- id: meae.congressional.congress08.national.county
  name: National 8th Congress
  type: previous
- id: meae.congressional.congress10.national.county
  name: National 10th Congress
  type: next
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
map_id <- "meae.congressional.congress09.national.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_national_map_data() %>%
  filter(id != "cts_wr") %>% 
  filter(id != "gas_nca") %>% 
  filter(id != "ohs_nca2") %>% 
   filter(id != "scs_nca5") %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage)) %>%
  filter(id != "tns_nca3",
         id != "tns_nca4") %>% 
  filter(id != "mss_jefferson",
         id != "mss_adams",
         id != "mss_claiborne",
         id != "mss_wilkinson",
         id != "mss_nca1") %>%
  filter(id != "als_washington") %>%
  filter(id != "ins_knox",
         id != "ins_clark",
         id != "ins_dearborn") %>%
  filter(id != "ils_stclair",
         id != "ils_randolph") %>%
  filter(id != "nwt",
         id != "int_wayne",
         id != "uft",
         id != "lap") %>%
  map_national(congress = 9)
```

</div>

<div class="results-table">

</div>
