---
meae-id: meae.congressional.congress13.md.county
type: congressional
level: state
state: Maryland
geography: county
congressnum: 13
congressordinal: 13th
title: '13th Congress: Maryland 1812'
year: 1812
legend: fed-vs-rep
nnv:
- id: md.uscongress1.1812
  name: MD US Congress 1812 District 1
- id: md.uscongress2.1812
  name: MD US Congress 1812 District 2
- id: md.uscongress3.1812
  name: MD US Congress 1812 District 3
- id: md.uscongress4.1812
  name: MD US Congress 1812 District 4
- id: md.uscongress5.1812
  name: MD US Congress 1812 District 5
- id: md.uscongress6.1812
  name: MD US Congress 1812 District 6
- id: md.uscongress7.1812
  name: MD US Congress 1812 District 7
- id: md.uscongress8.1812
  name: MD US Congress 1812 District 8
related-maps:
- id: meae.congressional.congress12.md.county
  name: MD 12th Congress
  type: previous
- id: meae.congressional.congress14.md.county
  name: MD 14th Congress
  type: next
- id: meae.congressional.congress13.national.county
  name: National 13th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress13.md.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote,
  "Baltimore", 39.30021, -76.61052, 0, 1.0, 0, 6933)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px", cities = FALSE) %>%
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 
```

</div>

Maryland elected three Federalists and six Democratic-Republicans to the Thirteenth Congress. 

Maryland used a district system for electing members to Congress. Each district elected one member of Congress except District 5, which elected two members.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
