---
meae-id: meae.congressional.congress04.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 4
congressordinal: 4th
title: '4th Congress: Vermont 1795'
year: 1795
legend: fed-vs-anti
nnv:
- id: vt.uscongress.secondballot.westerndistrict.1795
  name: VT US Congress 1795 District 1
- id: vt.uscongress.secondballot.easterndistrict.1795
  name: VT US Congress 1795 District 2
related-maps:
- id: meae.congressional.congress03.vt.county
  name: VT 3rd Congress
  type: previous
- id: meae.congressional.congress05.vt.county
  name: VT 5th Congress
  type: next
- id: meae.congressional.congress04.national.district
  name: National 4th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress04.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties()
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>