---
meae-id: meae.congressional.congress01.de.county
type: congressional
level: state
state: Delaware
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: Delaware 1789'
year: 1789
legend: fed-vs-anti
nnv:
- id: de.uscongress.1789
  name: DE US Congress 1789 At Large
related-maps:
- id: meae.congressional.congress02.de.county
  name: DE 2nd Congress
  type: next
# - id: meae.congressional.congress01.national.district
#   name: National 1st Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress01.de.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px")
```

</div>

Delaware elected a Federalist to the First Congress.

Delaware used a state-wide at-large system to elect members of Congress. Voters cast two votes in the election. The first had to be for a candidate from their home county and the second for a candidate from a different county. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>% 
  results_to_table() %>% 
  cat()
```

</div>
