---
meae-id: meae.congressional.congress06.va.county
type: congressional
level: state
state: Virginia
geography: county
congressnum: 6
congressordinal: 6th
title: '6th Congress: Virginia 1799'
year: 1799
legend: fed-vs-rep
nnv:
- id: va.uscongress.1.1799
  name: VA US Congress 1799 District 1
- id: va.uscongress.2.1799
  name: VA US Congress 1799 District 2
- id: va.uscongress.3.1799
  name: VA US Congress 1799 District 3
- id: va.uscongress.4.1799
  name: VA US Congress 1799 District 4
- id: va.uscongress.5.1799
  name: VA US Congress 1799 District 5
- id: va.uscongress.6.1799
  name: VA US Congress 1799 District 6
- id: va.uscongress.7.1799
  name: VA US Congress 1799 District 7
- id: va.uscongress.8.1799
  name: VA US Congress 1799 District 8
- id: va.uscongress.9.1799
  name: VA US Congress 1799 District 9
- id: va.uscongress.10.1799
  name: VA US Congress 1799 District 10
- id: va.uscongress.11.1799
  name: VA US Congress 1799 District 11
- id: va.uscongress.12.1799
  name: VA US Congress 1799 District 12
- id: va.uscongress.13.1799
  name: VA US Congress 1799 District 13
- id: va.uscongress.14.1799
  name: VA US Congress 1799 District 14
- id: va.uscongress.15.1799
  name: VA US Congress 1799 District 15
- id: va.uscongress.16.1799
  name: VA US Congress 1799 District 16
- id: va.uscongress.17.1799
  name: VA US Congress 1799 District 17
- id: va.uscongress.18.1799
  name: VA US Congress 1799 District 18
- id: va.uscongress.19.1799
  name: VA US Congress 1799 District 19
related-maps:
- id: meae.congressional.congress05.va.county
  name: VA 5th Congress
  type: previous
- id: meae.congressional.congress07.va.county
  name: VA 7th Congress
  type: next
# - id: meae.congressional.congress06.national.district
#   name: National 6th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress06.va.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "550px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
