---
meae-id: meae.congressional.congress09.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 9
congressordinal: 9th
title: '9th Congress: Georgia 1804'
year: 1804
legend: fed-vs-rep
nnv:
- id: ga.uscongress.1804
  name: GA US Congress 1804 At Large
related-maps:
- id: meae.congressional.congress08.ga.county
  name: GA 8th Congress
  type: previous
- id: meae.congressional.congress010.ga.county
  name: GA 10th Congress
  type: next
# - id: meae.congressional.congress09.national.district
#   name: National 9th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress09.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "gas_nca") %>% 
  map_counties(height = "500px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
