---
meae-id: meae.staterepresentative.1800.nj.county
type: state-rep
level: state
state: New Jersey
geography: county
title: 'New Jersey General Assembly, 1800'
year: 1800
legend: fed-vs-rep
nnv:
- id: nj.generalassembly.bergen.1800
  name: NJ General Assembly 1800, Bergen County
- id: nj.generalassembly.cumberland.1800
  name: NJ General Assembly 1800, Cumberland County
- id: nj.generalassembly.essex.1800
  name: NJ General Assembly 1800, Essex County
- id: nj.generalassembly.gloucester.1800
  name: NJ General Assembly 1800, Gloucester County
- id: nj.generalassembly.hunterdon.1800
  name: NJ General Assembly 1800, Hunterdon County
- id: nj.generalassembly.middlesex.1800
  name: NJ General Assembly 1800, Middlesex County
- id: nj.generalassembly.monmouth.1800
  name: NJ General Assembly 1800, Monmouth County            
- id: nj.generalassembly.morris.1800
  name: NJ General Assembly 1800, Morris County
- id: nj.generalassembly.salem.1800
  name: NJ General Assembly 1800, Salem County
- id: nj.generalassembly.somerset.1800
  name: NJ General Assembly 1800, Somerset County
- id: nj.generalassembly.sussex.1800
  name: NJ General Assembly 1800, Sussex County        
related-maps:
- id: meae.staterepresentative.1801.nj.county
  name: NJ 1801 General Assembly
  type: next
- id: meae.congressional.congress07.nj.county
  name: NJ 7th Congress
  type: congressional
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.staterepresentative.1800.nj.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data(election_date = "1800-10-01") %>%
  map_counties(height = "700px")
```

</div>

Map Text

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
