---
meae-id: meae.congressional.congress18.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 18
congressordinal: 18th
title: '18th Congress: Vermont 1822'
year: 1822
legend: fed-vs-rep
nnv:
- id: vt.uscongress.1822
  name: VT US Congress 1822 At Large
related-maps:
- id: meae.congressional.congress17.vt.county
  name: VT 17th Congress
  type: previous
- id: meae.congressional.congress19.vt.county
  name: VT 19th Congress
  type: next
- id: meae.congressional.congress18.national.county
  name: National 18th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress18.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px", congress = 18)
```

</div>

Vermont elected five Democratic-Republicans to the Eighteenth Congress.

Following the 1820 Census, Vermont lost one seat in the House of Representatives.

Vermont again switched to a statewide at-large system for electing members to Congress.

In 1824, a [special election](https://elections.lib.tufts.edu/catalog/tufts:vt.uscongress.special.1824) was held in which Henry Olin was elected to replace Charles Rich, who had died. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
