---
meae-id: meae.congressional.congress02.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 2
congressordinal: 2nd
title: '2nd Congress: Georgia 1791'
year: 1791
legend: fed-vs-anti
nnv:
- id: ga.uscongress.SouthernDistrict.1791
  name: GA US Congress 1791 District 1
- id: ga.uscongress.MiddleDistrict.1791
  name: GA US Congress 1791 District 2
- id: ga.uscongress.NorthernDistrict.1791
  name: GA US Congress 1791 District 3
related-maps:
- id: meae.congressional.congress01.ga.county
  name: GA 1st Congress
  type: previous
- id: meae.congressional.congress03.ga.county
  name: GA 3rd Congress
  type: next
- id: meae.congressional.congress02.national.district
  name: National 2nd Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress02.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px") %>% 
  setView(lng = -81.492, lat = 32.348, zoom = 7)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
