---
meae-id: meae.congressional.congress16.la.county
type: congressional
level: state
state: Louisiana
geography: county
congressnum: 16
congressordinal: 16th
title: '16th Congress: Louisiana 1818'
year: 1818
legend: fed-vs-anti
nnv:
- id: la.uscongress.1818
  name: LA US Congress 1818 At Large
related-maps:
- id: meae.congressional.congress15.la.county
  name: LA 15th Congress
  type: previous
- id: meae.congressional.congress17.la.county
  name: LA 17th Congress
  type: next
- id: meae.congressional.congress16.national.district
  name: National 16th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress16.la.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~demrep_percentage, ~other_percentage, ~demrep_vote, ~other_vote,
  "New Orleans", 30.0686, -89.9390, 0.879, 0.121, 655, 90)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(!is.na(state_abbr),
          cross_ref != "New to dataset") %>%
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage), 
          cnty_type == "Parish") %>% 
  map_counties(cities = FALSE, height = "600px") %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
               fillColor = mappingelections:::poli_chrome(cities),
               opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)<br/>",
                                 "Unaffiliated or other parties: ", other_percentage * 100,
                                 "% (", 
                                 prettyNum(other_vote, big.mark = ","), 
                                 " votes)"),
                 label = ~city)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
