---
meae-id: meae.congressional.congress14.de.county
type: congressional
level: state
state: Delaware
geography: county
congressnum: 14
congressordinal: 14th
title: '14th Congress: Delaware 1814'
year: 1814
legend: fed-vs-rep
nnv:
- id: de.uscongress.1814
  name: DE US Congress 1814 At Large
related-maps:
- id: meae.congressional.congress13.de.county
  name: DE 13th Congress
  type: previous
- id: meae.congressional.congress15.de.county
  name: DE 15th Congress
  type: next
- id: meae.congressional.congress14.national.county
  name: National 14th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress14.de.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px")
```

</div>

Delaware elected two Federalist to the Fourteenth Congress.

Delaware used a statewide at-large system for electing members to Congress. Delaware’s election law required that voters select two candidates, with one residing in the voter’s own county, and the other residing in one of the state's other two counties. Two at-large winners were elected.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
