---
meae-id: meae.congressional.congress02.national.county
type: congressional
level: national
geography: county
congressnum: 2
congressordinal: 2nd
title: '2nd Congress: National, 1790-1791'
year: 1789
legend: 'congress-2'
related-maps:
- id: meae.congressional.congress01.national.county
  name: National 1st Congress
  type: previous
- id: meae.congressional.congress03.national.county
  name: National 3rd Congress
  type: next
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress02.national.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_national_map_data() %>%
  filter(id != "cts_wr") %>% 
  filter(id != "gas_nca") %>% 
  filter(id != "ncs_nca5") %>% 
  filter(id != "scs_nca5",
         is.na(demrep_vote)) %>%
  filter(id != "tns_nca1",
         id != "tns_nca2",
         id != "tns_washington",
         id != "tns_sullivan",
         id != "tns_greene",
         id != "tns_hawkins",
         id != "tns_sumner",
         id != "tns_davidson",
         id != "tns_tennessee") %>% 
  filter(id != "ohs_washington") %>%
  filter(id != "nwt") %>%
  map_national(congress = 2)
```

</div>

<div class="results-table">

</div>
