---
meae-id: meae.congressional.congress03.ma.county
type: congressional
level: state
state: Massachusetts
geography: county
congressnum: 3
congressordinal: 3rd
title: '3rd Congress: Massachusetts 1793'
year: 1793
legend: fed-vs-anti
nnv:
- id: ma.uscongress.1.ballot3.1793
  name: MA US Congress 1793 District 1
- id: ma.uscongress.1.essex.1792
  name: MA US Congress 1792 District 1
- id: ma.uscongress.1.middlesex.1792
  name: MA US Congress 1792 District 1
- id: ma.uscongress.1.suffolk.1792
  name: MA US Congress 1792 District 1
- id: ma.uscongress.2.ballot3.1793
  name: MA US Congress 1793 District 2
- id: ma.uscongress.2.berkshire.1792
  name: MA US Congress 1792 District 2
- id: ma.uscongress.2.hampshire.ballot3.1793
  name: MA US Congress 1793 District 2
- id: ma.uscongress.2.worcester.1792
  name: MA US Congress 1792 District 2
- id: ma.uscongress.3.barnstableplymouth.ballot2.1793
  name: MA US Congress 1793 District 3
- id: ma.uscongress.3.bristoldukesnantucket.1792
  name: MA US Congress 1792 District 3
- id: ma.uscongress.4.cumberland.ballot3.1793
  name: MA US Congress 1793 District 4
- id: ma.uscongress.4.lincolnhancockwashington.ballot2.1793
  name: MA US Congress 1793 District 4
- id: ma.uscongress.4.york.1792
  name: MA US Congress 1792 District 4
- id: ma.uscongress.atlarge.1792
  name: MA US Congress 1792 District NA
related-maps:
- id: meae.congressional.congress02.ma.county
  name: MA 2nd Congress
  type: previous
- id: meae.congressional.congress04.ma.county
  name: MA 4th Congress
  type: next
- id: meae.congressional.congress03.national.district
  name: National 3rd Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress03.ma.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(cities = 2) %>% 
  fitBounds(-73.508, 41.186, -69.861, 44.25)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
meae_congress_candidate_totals %>% 
  filter(meae_id == map_id) %>% 
  results_to_table() %>%
  cat()
```

</div>
