---
meae-id: meae.congressional.congress02.sc.county
type: congressional
level: state
state: South Carolina
geography: county
congressnum: 2
congressordinal: 2nd
title: '2nd Congress: South Carolina 1790'
year: 1790
legend: fed-vs-anti
nnv:
- id: sc.uscongress.district1.1790
  name: SC US Congress 1790 District 1
- id: sc.uscongress.district2.1790
  name: SC US Congress 1790 District 2
- id: sc.uscongress.district3.1790
  name: SC US Congress 1790 District 3
- id: sc.uscongress.district4.1790
  name: SC US Congress 1790 District 4
- id: sc.uscongress.district5.1790
  name: SC US Congress 1790 District 5
related-maps:
- id: meae.congressional.congress01.sc.county
  name: SC 1st Congress
  type: previous
- id: meae.congressional.congress03.sc.county
  name: SC 3rd Congress
  type: next
- id: meae.congressional.congress02.national.county
  name: National 2nd Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress02.sc.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%   
  filter(id != "scs_nca5",
         is.na(demrep_vote)) %>% 
  map_counties(height = "600px", congress = 2)
```

</div>

South Carolina elected three Federalists and two Anti-Federalists to the Second Congress.

Most of South Carolina’s parishes cannot be mapped because there are insufficient returns at the parish level.

South Carolina used a district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
