---
meae-id: meae.congressional.congress09.va.county
type: congressional
level: state
state: Virginia
geography: county
congressnum: 9
congressordinal: 9th
title: '9th Congress: Virginia 1805'
year: 1805
legend: dissrep
nnv:
- id: va.uscongress.1.1805
  name: VA US Congress 1805 District 1
- id: va.uscongress.2.1805
  name: VA US Congress 1805 District 2
- id: va.uscongress.3.1805
  name: VA US Congress 1805 District 3
- id: va.uscongress.4.1805
  name: VA US Congress 1805 District 4
- id: va.uscongress.5.1805
  name: VA US Congress 1805 District 5
- id: va.uscongress.6.1805
  name: VA US Congress 1805 District 6
- id: va.uscongress.7.1805
  name: VA US Congress 1805 District 7
- id: va.uscongress.8.1805
  name: VA US Congress 1805 District 8
- id: va.uscongress.9.1805
  name: VA US Congress 1805 District 9
- id: va.uscongress.10.1805
  name: VA US Congress 1805 District 10
- id: va.uscongress.11.1805
  name: VA US Congress 1805 District 11
- id: va.uscongress.12.1805
  name: VA US Congress 1805 District 12
- id: va.uscongress.13.1805
  name: VA US Congress 1805 District 13
- id: va.uscongress.14.1805
  name: VA US Congress 1805 District 14
- id: va.uscongress.15.1805
  name: VA US Congress 1805 District 15
- id: va.uscongress.16.1805
  name: VA US Congress 1805 District 16
- id: va.uscongress.17.1805
  name: VA US Congress 1805 District 17
- id: va.uscongress.18.1805
  name: VA US Congress 1805 District 18
- id: va.uscongress.19.1805
  name: VA US Congress 1805 District 19
- id: va.uscongress.20.1805
  name: VA US Congress 1805 District 20
- id: va.uscongress.21.1805
  name: VA US Congress 1805 District 21
- id: va.uscongress.22.1805
  name: VA US Congress 1805 District 22
related-maps:
- id: meae.congressional.congress08.va.county
  name: VA 8th Congress
  type: previous
- id: meae.congressional.congress10.va.county
  name: VA 10th Congress
  type: next
# - id: meae.congressional.congress09.national.district
#   name: National 9th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress09.va.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "550px", congress = 9)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
