---
title: '3rd Congress: Virginia 1793'
congressnum: 3
congressordinal: 3rd
output:
  html_document:
    theme: default
  md_document:
    variant: markdown
layout: maps-show
legend: fed-vs-anti
level: state
meae-id: meae.congressional.congress03.va.county
nnv:
- id: va.uscongress.1793
  name: VA US Congress 1793 District 1
- id: va.uscongress.2.1793
  name: VA US Congress 1793 District 2
- id: va.uscongress.3.1792
  name: VA US Congress 1792 District 3
- id: va.uscongress.3.1793
  name: VA US Congress 1793 District 3
- id: va.uscongress.4.1793
  name: VA US Congress 1793 District 4
- id: va.uscongress.5.1793
  name: VA US Congress 1793 District 5
- id: va.uscongress.6.1793
  name: VA US Congress 1793 District 6
- id: va.uscongress.7.1793
  name: VA US Congress 1793 District 7
- id: va.uscongress.8.1793
  name: VA US Congress 1793 District 8
- id: va.uscongress.9.1793
  name: VA US Congress 1793 District 9
- id: va.uscongress.10.1793
  name: VA US Congress 1793 District 10
- id: va.uscongress.11.1793
  name: VA US Congress 1793 District 11
- id: va.uscongress.12.1793
  name: VA US Congress 1793 District 12
- id: va.uscongress.13.1793
  name: VA US Congress 1793 District 13
- id: va.uscongress.14.1793
  name: VA US Congress 1793 District 14
- id: va.uscongress.15.1793
  name: VA US Congress 1793 District 15
- id: va.uscongress.16.1793
  name: VA US Congress 1793 District 16
- id: va.uscongress.17.1793
  name: VA US Congress 1793 District 17
- id: va.uscongress.18.1793
  name: VA US Congress 1793 District 18
- id: va.uscongress.19.1793
  name: VA US Congress 1793 District 19
geography: county
related-maps:
- id: meae.congressional.congress02.va.county
  name: VA 2nd Congress
  type: previous
- id: meae.congressional.congress04.va.county
  name: VA 4th Congress
  type: next
- id: meae.congressional.congress03.national.district
  name: National 3rd Congress
  type: national
state: Virginia
always_allow_html: yes
type: congressional
year: 1793
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress03.va.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "405px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
