---
meae-id: meae.congressional.congress12.ri.county
type: congressional
level: state
state: Rhode Island
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: Rhode Island 1810'
year: 1810
legend: fed-vs-rep
nnv:
- id: ri.uscongress.1810
  name: RI US Congress 1810 At Large
related-maps:
- id: meae.congressional.congress11.ri.county
  name: RI 11th Congress
  type: previous
- id: meae.congressional.congress13.ri.county
  name: RI 13th Congress
  type: next
#- id: meae.congressional.congress12.national.district
#  name: National 12th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.ri.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", congress = 12)
```

</div>

Rhode Island elected two Federalists to the Twelfth Congress.

Rhode Island used a statewide at-large method for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
