---
meae-id: meae.congressional.congress01.nj.county
type: congressional
level: state
state: New Jersey
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: New Jersey 1789'
year: 1789
nnv:
- id: nj.uscongress.1789
  name: NJ US Congress 1789 At Large
related-maps:
- id: meae.congressional.congress02.nj.county
  name: NJ 2nd Congress
  type: next
- id: meae.congressional.congress01.national.district
  name: National 1st Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress01.nj.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "700px")
```

</div>

The results from Cumberland County were included in the reports from Cape May County.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table(keep_percentage = 0.01) %>%
  cat()
```

</div>
