---
title: '5th Congress: Rhode Island 1796'
congressnum: 5
congressordinal: 5th
output:
  html_document:
    theme: default
  md_document:
    variant: markdown
layout: maps-show
legend: fed-vs-anti
level: state
meae-id: meae.congressional.congress05.ri.county
nnv:
- id: ri.uscongress.secondcongressmen.1796
  name: RI US Congress 1796 District NA
- id: ri.uscongress.specialelection.1796
  name: RI US Congress 1796 District NA
geography: county
related-maps:
- id: meae.congressional.congress04.ri.county
  name: RI 4th Congress
  type: previous
- id: meae.congressional.congress06.ri.county
  name: RI 6th Congress
  type: next
- id: meae.congressional.congress05.national.district
  name: National 5th Congress
  type: national
state: Rhode Island
always_allow_html: yes
type: congressional
year: 1796
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress05.ri.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  map_counties(height = "300px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
