---
meae-id: meae.congressional.congress15.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 15
congressordinal: 15th
title: '15th Congress: Tennessee 1817'
year: 1817
legend: fed-vs-rep
nnv:
- id: tn.congress.1.1817
  name: TN US Congress 1817 District 1
- id: tn.congress.2.1817
  name: TN US Congress 1817 District 2
- id: tn.congress.3.1817
  name: TN US Congress 1817 District 3
- id: tn.congress.4.1817
  name: TN US Congress 1817 District 4
- id: tn.congress.5.1817
  name: TN US Congress 1817 District 5
- id: tn.congress.6.1817
  name: TN US Congress 1817 District 6
related-maps:
- id: meae.congressional.congress14.tn.county
  name: TN 14th Congress
  type: previous
- id: meae.congressional.congress16.tn.county
  name: TN 16th Congress
  type: next
#- id: meae.congressional.congress15.national.district
#  name: National 15th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress15.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
    filter(id != "tns_nca4",
           id != "tns_nca7") %>% 
  map_counties(height = "300px", congress = 15)
```

</div>

Tennessee elected six Democratic-Republicans to the Fifteenth Congress.

Tennessee used a district system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
