---
meae-id: meae.congressional.congress12.pa.county
type: congressional
level: state
state: Pennsylvania
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: Pennsylvania 1810'
year: 1810
legend: fed-vs-rep
nnv:
- id: pa.uscongress1.1810
  name: PA US Congress 1810 District 1
- id: pa.uscongress2.1810
  name: PA US Congress 1810 District 2
- id: pa.uscongress3.1810
  name: PA US Congress 1810 District 3
- id: pa.uscongress4.1810
  name: PA US Congress 1810 District 4
- id: pa.uscongress5.1810
  name: PA US Congress 1810 District 5
- id: pa.uscongress6.1810
  name: PA US Congress 1810 District 6
- id: pa.uscongress7.1810
  name: PA US Congress 1810 District 7
- id: pa.uscongress8.1810
  name: PA US Congress 1810 District 8
- id: pa.uscongress9.1810
  name: PA US Congress 1810 District 9
- id: pa.uscongress10.1810
  name: PA US Congress 1810 District 10
- id: pa.uscongress11.1810
  name: PA US Congress 1810 District 11
related-maps:
- id: meae.congressional.congress11.pa.county
  name: PA 11th Congress
  type: previous
- id: meae.congressional.congress13.pa.county
  name: PA 13th Congress
  type: next
#- id: meae.congressional.congress12.national.district
#  name: National 12th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.pa.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~other_percentage, ~federalist_vote, ~demrep_vote, ~other_vote,
    "Philadelphia", 39.9526, -75.1652, 0.401, 0.251, 0.348, 7221, 4524, 6270)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
 map_counties(height = "500px", cities = 0, congress = 12) %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)<br/>",
                                 "Unaffiliated or other party: ", other_percentage * 100,
                                 "% (", 
                                 prettyNum(other_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 
```

</div>

Pennsylvania elected two Federalists and sixteen Democratic-Republicans to the Twelfth Congress.

The map for this election is incomplete due to the lack of returns in several counties.

Pennsylvania used the district system for electing members to Congress. Districts 1, 2, and 3 each elected three representatives. District 4 elected two representatives.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
