---
meae-id: meae.congressional.congress16.ct.county
type: congressional
level: state
state: Connecticut
geography: county
congressnum: 16
congressordinal: 16th
title: '16th Congress: Connecticut 1818'
year: 1818
legend: fed-vs-rep
nnv:
- id: ct.congress.1818
  name: CT US Congress 1818 At Large
related-maps:
- id: meae.congressional.congress15.ct.county
  name: CT 15th Congress
  type: previous
- id: meae.congressional.congress17.ct.county
  name: CT 17th Congress
  type: next
- id: meae.congressional.congress16.national.county
  name: National 16th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress16.ct.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "350px", congress = 16)
```

</div>

Connecticut elected seven Democratic-Republicans to the Sixteenth Congress. James Stevens received support from both parties.

Connecticut used a statewide at-large system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
