---
meae-id: meae.congressional.congress04.sc.county
type: congressional
level: state
state: South Carolina
geography: county
congressnum: 4
congressordinal: 4th
title: '4th Congress: South Carolina 1794'
year: 1794
legend: fed-vs-rep
nnv:
- id: sc.uscongress.district1.1794
  name: SC US Congress 1794 District 1
- id: sc.uscongress.district3.1794
  name: SC US Congress 1794 District 5
related-maps:
- id: meae.congressional.congress03.sc.county
  name: SC 3rd Congress
  type: previous
- id: meae.congressional.congress05.sc.county
  name: SC 5th Congress
  type: next
# - id: meae.congressional.congress04.national.district
#   name: National 4th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress04.sc.county"
cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote,
  "Charleston", 32.7765, -79.9311, 0.874, 0.126, 588, 85)

```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  map_counties(cities = FALSE, height = "600px", congress = 4) %>% 
   addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 

```

</div>

South Carolina elected two Federalists and four Democratic-Republicans to the Fourth Congress.

Many returns are missing from this election.

In January 1795, a [special election](https://elections.lib.tufts.edu/catalog/tufts:sc.uscongress.specialelection.1795) was held in which Wade Hampton was elected to replace John Barnwell, who had been elected but declined to serve. Wade Hampton is included in the table below.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
meae_congress_candidate_totals %>% 
  filter(meae_id == map_id) %>% 
  results_to_table() %>%
  cat()
```

</div>
