---
meae-id: meae.congressional.congress05.pa.county
type: congressional
level: state
state: Pennsylvania
geography: county
congressnum: 5
congressordinal: 5th
title: '5th Congress: Pennsylvania 1796'
year: 1796
legend: fed-vs-rep
nnv:
- id: pa.uscongress1.1796
  name: PA US Congress 1796 District 1
- id: pa.uscongress2.1796
  name: PA US Congress 1796 District 2
- id: pa.uscongress3.1796
  name: PA US Congress 1796 District 3
- id: pa.uscongress4.1796
  name: PA US Congress 1796 District 4
- id: pa.uscongress5.1796
  name: PA US Congress 1796 District 5
- id: pa.uscongress6.1796
  name: PA US Congress 1796 District 6
- id: pa.uscongress7.1796
  name: PA US Congress 1796 District 7
- id: pa.uscongress8.1796
  name: PA US Congress 1796 District 8
- id: pa.uscongress9.1796
  name: PA US Congress 1796 District 9
- id: pa.uscongress10.1796
  name: PA US Congress 1796 District 10
- id: pa.uscongress11.1796
  name: PA US Congress 1796 District 11
- id: pa.uscongress12.1796
  name: PA US Congress 1796 District 12
related-maps:
- id: meae.congressional.congress04.pa.county
  name: PA 4th Congress
  type: previous
# - id: meae.congressional.congress06.pa.county
#   name: PA 6th Congress
#   type: next
# - id: meae.congressional.congress05.national.district
#   name: National 5th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress05.pa.county"
cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote,
  "Philadelphia", 39.9526, -75.1652, 0.488, 0.512, 1432, 1502)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", cities = 0) %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
