---
meae-id: meae.congressional.congress05.national.county
type: congressional
level: national
geography: county
congressnum: 5
congressordinal: 5th
title: '5th Congress: National, 1796-1797'
year: 1796
legend: 'fed-vs-rep'
related-maps:
- id: meae.congressional.congress04.national.county
  name: National 4th Congress
  type: previous
- id: meae.congressional.congress06.national.county
  name: National 6th Congress
  type: next
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
map_id <- "meae.congressional.congress05.national.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_national_map_data() %>%
  filter(id != "cts_wr") %>% 
  filter(id != "gas_nca") %>% 
  filter(id != "scs_nca5") %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage)) %>%
  filter(id != "tns_nca1",
          id != "tns_nca2") %>% 
  map_national(congress = 5)
```

</div>

<div class="results-table">

</div>
