---
meae-id: meae.congressional.congress06.ny.county
type: congressional
level: state
state: New York
geography: county
congressnum: 6
congressordinal: 6th
title: '6th Congress: New York 1798'
year: 1798
legend: fed-vs-rep
nnv:
- id: ny.uscongress1.1798
  name: NY US Congress 1798 District 1
- id: ny.uscongress2.1798
  name: NY US Congress 1798 District 2
- id: ny.uscongress3.1798
  name: NY US Congress 1798 District 3
- id: ny.uscongress4.1798
  name: NY US Congress 1798 District 4
- id: ny.uscongress5.1798
  name: NY US Congress 1798 District 5
- id: ny.uscongress6.1798
  name: NY US Congress 1798 District 6
- id: ny.uscongress7.1798
  name: NY US Congress 1798 District 7
- id: ny.uscongress8.1798
  name: NY US Congress 1798 District 8
- id: ny.uscongress9.1798
  name: NY US Congress 1798 District 9
- id: ny.uscongress10.1798
  name: NY US Congress 1798 District 10
related-maps:
- id: meae.congressional.congress05.ny.county
  name: NY 5th Congress
  type: previous
- id: meae.congressional.congress07.ny.county
  name: NY 7th Congress
  type: next
# - id: meae.congressional.congress06.national.district
#   name: National 6th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress06.ny.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "550px")
```

</div>

New York elected four Federalists and six Democratic-Republicans to the Sixth Congress.

New York used the district system for electing members to Congress.

In December 1799, a [special election](https://elections.lib.tufts.edu/catalog/tufts:ny.specialuscongress1.1799) was held in which Democratic-Republican John Smith was elected to replace Jonathan N. Havens, who died in office.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
