---
meae-id: meae.congressional.congress03.ny.county
type: congressional
level: state
state: New York
geography: county
congressnum: 3
congressordinal: 3rd
title: '3rd Congress: New York 1793'
year: 1793
legend: fed-vs-rep
nnv:
- id: ny.uscongress1.1793
  name: NY US Congress 1793 District 1
- id: ny.uscongress2.1793
  name: NY US Congress 1793 District 2
- id: ny.uscongress3.1793
  name: NY US Congress 1793 District 3
- id: ny.uscongress4.1793
  name: NY US Congress 1793 District 4
- id: ny.uscongress5.1793
  name: NY US Congress 1793 District 5
- id: ny.uscongress6.1793
  name: NY US Congress 1793 District 6
- id: ny.uscongress7.1793
  name: NY US Congress 1793 District 7
- id: ny.uscongress8.1793
  name: NY US Congress 1793 District 8
- id: ny.uscongress9.1793
  name: NY US Congress 1793 District 9
- id: ny.uscongress10.1793
  name: NY US Congress 1793 District 10
related-maps:
- id: meae.congressional.congress02.ny.county
  name: NY 2nd Congress
  type: previous
- id: meae.congressional.congress04.ny.county
  name: NY 4th Congress
  type: next
# - id: meae.congressional.congress03.national.district
#   name: National 3rd Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress03.ny.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>% 
  get_county_map_data() %>% 
  map_counties(height = "700px")
```

</div>

New York elected seven Federalists and three Democratic-Republicans to the Third Congress.

New York used a district system for electing members to Congress. After the 1790 Census, New York gained four seats in the House of Representatives.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
