---
meae-id: meae.congressional.congress12.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: Vermont 1810'
year: 1810
legend: fed-vs-rep
nnv:
- id: vt.uscongress.southwest.1810
  name: VT US Congress 1810 District 1
- id: vt.uscongress.southeast.1810
  name: VT US Congress 1810 District 2
- id: vt.uscongress.northeast.1810
  name: VT US Congress 1810 District 3
- id: vt.uscongress.northwest.1810
  name: VT US Congress 1810 District 4
related-maps:
- id: meae.congressional.congress11.vt.county
  name: VT 11th Congress
  type: previous
- id: meae.congressional.congress13.vt.county
  name: VT 13th Congress
  type: next
#- id: meae.congressional.congress12.national.district
#  name: National 12th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px", congress = 12)
```

</div>

Vermont elected one Federalists and three Democratic-Republican to the Twelfth Congress.

Vermont used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
