---
meae-id: meae.congressional.congress03.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 3
congressordinal: 3rd
title: '3rd Congress: Georgia 1792'
year: 1792
legend: fed-vs-rep
nnv:
- id: ga.uscongress.1792
  name: GA US Congress 1792 At Large
related-maps:
- id: meae.congressional.congress02.ga.county
  name: GA 2nd Congress
  type: previous
- id: meae.congressional.congress04.ga.county
  name: GA 4th Congress
  type: next
# - id: meae.congressional.congress03.national.district
#   name: National 3rd Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress03.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "gas_nca") %>% 
  map_counties(height = "500px")
```

</div>

Georgia elected one Democratic-Republican and one Federalist to the Third Congress.

Georgia used a state-wide at-large system for electing members to Congress. Its seats in Congress were decreased from three to two following the 1790 Census.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
