---
meae-id: meae.congressional.congress19.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 19
congressordinal: 19th
title: '19th Congress: Georgia 1824'
year: 1824
legend: congress-18-19
nnv:
- id: ga.uscongress.1824
  name: GA US Congress 1824 At Large
related-maps:
- id: meae.congressional.congress18.ga.county
  name: GA 18th Congress
  type: previous
- id: meae.congressional.congress19.national.county
  name: National 19th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress19.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "gas_nca") %>%
  map_counties(height = "550px")
```

</div>

Georgia elected seven Democratic-Republicans to the Nineteenth Congress. All seven of those Democratic-Republicans were part of a faction led by William Crawford.

The map for this election is incomplete due to the lack of returns in two counties. 

Georgia used a statewide at-large system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
