---
meae-id: meae.congressional.congress07.nh.county
type: congressional
level: state
state: New Hampshire
geography: county
congressnum: 7
congressordinal: 7th
title: '7th Congress: New Hampshire 1800'
year: 1800
legend: fed-vs-rep
nnv:
- id: nh.uscongress.1800
  name: NH US Congress 1800 At Large
related-maps:
- id: meae.congressional.congress06.nh.county
  name: NH 6th Congress
  type: previous
- id: meae.congressional.congress08.nh.county
  name: NH 8th Congress
  type: next
# - id: meae.congressional.congress07.national.district
#   name: National 7th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress07.nh.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "700px", congress = 7)
```

</div>

New Hampshire elected four Federalists to the Seventh Congress.

New Hampshire used a statewide at-large method for electing members to Congress.

In 1802, a [special election](https://elections.lib.tufts.edu/catalog/tufts:nh.uscongress.special.1802) was held in which Samuel Hunt was elected to replace Joseph Pierce, who had resigned from office.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table(keep_percentage = 0.01) %>%
  cat()
```

</div>
