---
meae-id: meae.congressional.congress14.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 14
congressordinal: 14th
title: '14th Congress: Georgia 1814'
year: 1814
legend: fed-vs-rep
nnv:
- id: ga.uscongress.1814
  name: GA US Congress 1814 At Large
related-maps:
- id: meae.congressional.congress13.ga.county
  name: GA 13th Congress
  type: previous
- id: meae.congressional.congress15.ga.county
  name: GA 15th Congress
  type: next
#- id: meae.congressional.congress14.national.district
#  name: National 14th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress14.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "gas_nca") %>% 
  map_counties(height = "525px")
```

</div>

Georgia elected six Democratic-Republicans to the Fourteenth Congress.

Georgia used a statewide at-large system for electing members to Congress.

In 1816, a [special election](https://elections.lib.tufts.edu/catalog/tufts:ga.specialuscongress.1816) was held in which Zadock Cook was elected to replace Alfred Cuthbert, who had resigned from office.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
