---
meae-id: meae.congressional.congress14.oh.county
type: congressional
level: state
state: Ohio
geography: county
congressnum: 14
congressordinal: 14th
title: '14th Congress: Ohio 1814'
year: 1814
legend: fed-vs-rep
nnv:
- id: oh.uscongress1.1814
  name: OH US Congress 1814 District 1
- id: oh.uscongress2.1814
  name: OH US Congress 1814 District 2
- id: oh.uscongress3.1814
  name: OH US Congress 1814 District 3
- id: oh.uscongress4.1814
  name: OH US Congress 1814 District 4
- id: oh.uscongress5.1814
  name: OH US Congress 1814 District 5
- id: oh.uscongress6.1814
  name: OH US Congress 1814 District 6
related-maps:
- id: meae.congressional.congress13.oh.county
  name: OH 13th Congress
  type: previous
- id: meae.congressional.congress15.oh.county
  name: OH 15th Congress
  type: next
#- id: meae.congressional.congress14.national.district
#  name: National 14th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress14.oh.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  filter(id != "ohs_nca4",
         id != "ohs_nca5") %>% 
  map_counties(height = "650px", congress = 14)
```

</div>

Ohio elected six Democratic-Republican to the Fourteenth Congress. 

Mapping this election is incomplete because of the lack of local returns in many areas.

Ohio used a district system for electing members to Congress. 

In 1816, a [special election](https://elections.lib.tufts.edu/catalog/tufts:oh.uscongress1.vacancy.1816) was held in which William H. Harrison was elected to replace John Mclean, who had resigned. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
