---
meae-id: meae.congressional.congress08.sc.county
type: congressional
level: state
state: South Carolina
geography: county
congressnum: 8
congressordinal: 8th
title: '8th Congress: South Carolina 1803'
year: 1803
legend: fed-vs-rep
nnv:
- id: sc.uscongress.charleston.1803
  name: SC US Congress 1803 District 1
- id: sc.uscongress.edgefield.1803
  name: SC US Congress 1803 District 2
- id: sc.uscongress.georgetown.1803
  name: SC US Congress 1803 District 3
- id: sc.uscongress.orangeburg.1803
  name: SC US Congress 1803 District 4
- id: sc.uscongress.sumter.1803
  name: SC US Congress 1803 District 5
- id: sc.uscongress.abbeville.1803
  name: SC US Congress 1803 District 6
- id: sc.uscongress.chester.1803
  name: SC US Congress 1803 District 7
- id: sc.uscongress.pendleton.1803
  name: SC US Congress 1803 District 8
related-maps:
- id: meae.congressional.congress07.sc.county
  name: SC 7th Congress
  type: previous
- id: meae.congressional.congress09.sc.county
  name: SC 9th Congress
  type: next
# - id: meae.congressional.congress08.national.district
#   name: National 8th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress08.sc.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote,
  "Charleston", 32.7765, -79.9311, 0.569, 0.431, 329, 249)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "scs_nca5") %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage)) %>%
  map_counties(cities = FALSE, height = "600px") %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
               fillColor = mappingelections:::poli_chrome(cities),
               opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 
```

</div>

South Carolina elected two Federalists and six Democratic-Republicans to the Eighth Congress.

The map for this election is incomplete due to the lack of returns at the parish or district level.

Following the 1800 Census, South Carolina gained two seats in the House of Representatives.

South Carolina used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
