---
meae-id: meae.congressional.congress05.va.county
type: congressional
level: state
state: Virginia
geography: county
congressnum: 5
congressordinal: 5th
title: '5th Congress: Virginia 1797'
year: 1797
legend: fed-vs-rep
nnv:
- id: va.uscongress.1.1797
  name: VA US Congress 1797 District 1
- id: va.uscongress.2.1797
  name: VA US Congress 1797 District 2
- id: va.uscongress.3.1797
  name: VA US Congress 1797 District 3
- id: va.uscongress.4.1797
  name: VA US Congress 1797 District 4
- id: va.uscongress.5.1797
  name: VA US Congress 1797 District 5
- id: va.uscongress.6.1797
  name: VA US Congress 1797 District 6
- id: va.uscongress.7.1797
  name: VA US Congress 1797 District 7
- id: va.uscongress.8.1797
  name: VA US Congress 1797 District 8
- id: va.uscongress.9.1797
  name: VA US Congress 1797 District 9
- id: va.uscongress.10.1797
  name: VA US Congress 1797 District 10
- id: va.uscongress.11.1797
  name: VA US Congress 1797 District 11
- id: va.uscongress.12.1797
  name: VA US Congress 1797 District 12
- id: va.uscongress.13.1797
  name: VA US Congress 1797 District 13
- id: va.uscongress.14.1797
  name: VA US Congress 1797 District 14
- id: va.uscongress.15.1797
  name: VA US Congress 1797 District 15
- id: va.uscongress.16.1797
  name: VA US Congress 1797 District 16
- id: va.uscongress.17.1797
  name: VA US Congress 1797 District 17
- id: va.uscongress.18.1797
  name: VA US Congress 1797 District 18
- id: va.uscongress.19.1797
  name: VA US Congress 1797 District 19
related-maps:
- id: meae.congressional.congress04.va.county
  name: VA 4th Congress
  type: previous
- id: meae.congressional.congress06.va.county
  name: VA 6th Congress
  type: next
# - id: meae.congressional.congress05.national.district
#   name: National 5th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress05.va.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "550px")
```

</div>

Virginia elected fifteen Democratic-Republicans and four Federalists to the Fifth Congress.

Virginia used the district system for electing members to Congress.
In 1798, Virginia held a [special election](https://elections.lib.tufts.edu/catalog/tufts:va.uscongress.9.special.1798) in which Joseph Eggleston was elected to replace William B. Giles, who resigned from office.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
