---
meae-id: meae.congressional.congress08.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 8
congressordinal: 8th
title: '8th Congress: Vermont 1802'
year: 1802
legend: fed-vs-rep
nnv:
- id: vt.uscongress.southwest.1802
  name: VT US Congress 1802 District 1
- id: vt.uscongress.southeast.secondballot.1803
  name: VT US Congress 1803 District 2
- id: vt.uscongress.northeast.1802
  name: VT US Congress 1802 District 3
- id: vt.uscongress.northwest.thirdballot.1803
  name: VT US Congress 1803 District 4
related-maps:
- id: meae.congressional.congress07.vt.county
  name: VT 7th Congress
  type: previous
- id: meae.congressional.congress09.vt.county
  name: VT 9th Congress
  type: next
# - id: meae.congressional.congress08.national.district
#   name: National 8th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress08.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px", congress = 8)
```

</div>

Vermont elected three Federalists and one Democratic-Republican to the Eighth Congress.

Following the 1800 Census, Vermont gained two seats in the House of Representatives.

Vermont used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
