---
meae-id: meae.congressional.congress07.ri.county
type: congressional
level: state
state: Rhode Island
geography: county
congressnum: 7
congressordinal: 7th
title: '7th Congress: Rhode Island 1800'
year: 1800
legend: fed-vs-rep
nnv:
- id: ri.uscongress.1800
  name: RI US Congress 1800 At Large 1st Ballot
- id: ri.uscongress.1801
  name: RI US Congress 1801 At Large 2nd Ballot
related-maps:
- id: meae.congressional.congress06.ri.county
  name: RI 6th Congress
  type: previous
- id: meae.congressional.congress08.ri.county
  name: RI 8th Congress
  type: next
# - id: meae.congressional.congress07.national.district
#   name: National 7th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress07.ri.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", congress = 7)
```

</div>

Rhode Island elected two Democratic-Republicans to the Seventh Congress.

Rhode Island used a statewide at-large method for electing a member to Congress. State law required a majority to elect. Joseph Stanton Jr. did not meet this requirement and a 2nd ballot was held resulting in his election. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
