---
meae-id: meae.congressional.congress16.al.county
type: congressional
level: state
state: Alabama
geography: county
congressnum: 16
congressordinal: 16th
title: '16th Congress: Alabama 1819'
year: 1819
legend: fed-vs-rep
nnv:
- id: al.congress.1819
  name: AL US Congress 1819 At Large
related-maps:
- id: meae.congressional.congress17.al.county
  name: AL 17th Congress
  type: next
#- id: meae.congressional.congress16.national.district
#  name: National 16th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress16.al.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data(election_date = "1819-12-15") %>%
  filter (id != "als_nca6",
          id != "als_nca7",
          id != "als_nca8",
          id != "als_nca9") %>% 
  map_counties()
```

</div>

Alabama elected one Democratic-Republican to the Sixteenth Congress.

Mapping this election is incomplete because of the lack of local returns in many areas.

Alabama used a statewide at-large system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
