---
meae-id: meae.congressional.congress19.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 19
congressordinal: 19th
title: '19th Congress: Tennessee 1825'
year: 1825
legend: congress-18-19
nnv:
- id: tn.congress.1st.1825
  name: TN US Congress 1825 District 1
- id: tn.congress.2nd.1825
  name: TN US Congress 1825 District 2
- id: tn.congress.3rd.1825
  name: TN US Congress 1825 District 3
- id: tn.congress.4th.1825
  name: TN US Congress 1825 District 4
- id: tn.congress.5th.1825
  name: TN US Congress 1825 District 5
- id: tn.congress.6th.1825
  name: TN US Congress 1825 District 6
- id: tn.congress.7th.1825
  name: TN US Congress 1825 District 7
- id: tn.congress.8th.1825
  name: TN US Congress 1825 District 8
- id: tn.congress.9th.1825
  name: TN US Congress 1825 District 9
related-maps:
- id: meae.congressional.congress18.tn.county
  name: TN 18th Congress
  type: previous
- id: meae.congressional.congress19.national.county
  name: National 19th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress19.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties()
```

</div>

Tennessee elected nine Democratic-Republicans to the Nineteenth Congress. All eight of those Democratic-Republicans were part of a faction led by Andrew Jackson.

The map for this election is incomplete due to the lack of returns in some counties.

Tennessee used a district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
