---
meae-id: meae.congressional.congress01.ma.county
type: congressional
level: state
state: Massachusetts
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: Massachusetts 1788'
year: 1788
legend: fed-vs-anti
nnv:
- id: ma.uscongress.1.1788
  name: MA US Congress 1788 District 1
- id: ma.uscongress.2.ballot2.1789
  name: MA US Congress 1789 District 2
- id: ma.uscongress.3.ballot2.1789
  name: MA US Congress 1789 District 3
- id: ma.uscongress.4.ballot5.1789
  name: MA US Congress 1789 District 4
- id: ma.uscongress.5.1788
  name: MA US Congress 1788 District 5
- id: ma.uscongress.6.1788
  name: MA US Congress 1788 District 6
- id: ma.uscongress.7.1788
  name: MA US Congress 1788 District 7
- id: ma.uscongress.8.ballot3.1789
  name: MA US Congress 1789 District 8
related-maps:
- id: meae.congressional.congress02.ma.county
  name: MA 2nd Congress
  type: next
# - id: meae.congressional.congress01.national.district
#   name: National 1st Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress01.ma.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  map_counties() %>% 
  fitBounds(-73.508, 41.186, -69.861, 43.75)
```

</div>

Massachusetts elected five Federalists, one Anti-Federalist, and two representatives unaffiliated with either party to the First Congress. Of the unaffiliated representatives, George Partridge favored the administration and Jonathan Grout was anti-administration. 

Massachusetts used a  district system to elect members of Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
