---
meae-id: meae.congressional.congress08.ny.county
type: congressional
level: state
state: new york
geography: county
congressnum: 8
title: Elections for the Eighth Congress in New York, 1803
caption: This is the brief description of the contents of the map.
legend_type: fed-vs-repub-percentage
nnv:
- id: ny.uscongress1.1802
  name: NY US Congress 1802 District 1
- id: ny.uscongress2.1802
  name: NY US Congress 1802 District 2
- id: ny.uscongress3.1802
  name: NY US Congress 1802 District 3
- id: ny.uscongress4.1802
  name: NY US Congress 1802 District 4
- id: ny.uscongress5.1802
  name: NY US Congress 1802 District 5
- id: ny.uscongress6.1802
  name: NY US Congress 1802 District 6
- id: ny.specialuscongress7.1803
  name: NY US Congress 1803 District 7
- id: ny.uscongress8.1802
  name: NY US Congress 1802 District 8
- id: ny.uscongress9.1802
  name: NY US Congress 1802 District 9
- id: ny.uscongress10.1802
  name: NY US Congress 1802 District 10
- id: ny.uscongress11.1802
  name: NY US Congress 1802 District 11
- id: ny.uscongress12.1802
  name: NY US Congress 1802 District 12
- id: ny.uscongress13.1802
  name: NY US Congress 1802 District 13
- id: ny.uscongress14.1802
  name: NY US Congress 1802 District 14
- id: ny.uscongress15.1802
  name: NY US Congress 1802 District 15
- id: ny.uscongress16.1802
  name: NY US Congress 1802 District 16
- id: ny.uscongress17.1802
  name: NY US Congress 1802 District 17
related-maps:
- id: meae.congressional.congress07.ny.county
  name: NY Seventh Congress
  type: previous
- id: meae.congressional.congress09.ny.county
  name: NY Ninth Congress
  type: next
- id: meae.congressional.congress08.national.district
  name: National Eighth Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

meae_id <- "meae.congressional.congress08.ny.county"
votes <- vote_counts(meae_id)
party_aggregates <- aggregate_party_votes(votes)
candidate_aggregates <- aggregate_candidate_votes(votes)
map_data <- join_to_spatial(party_aggregates)
```

<div class="map">

```{r election-map, echo = FALSE}
map_elections(map_data, legend = FALSE)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
cat(results_to_table(candidate_aggregates))
```

</div>

## About this election
