---
meae-id: meae.staterepresentative.1805.pa.county
type: state-rep
level: state
state: Pennsylvania
geography: county
title: 'Pennsylvania House of Representatives, 1805'
year: 1805
legend: dissrep
nnv:
- id: pa.assembly.adams.1805
  name: PA House of Representatives 1805, Adams County
- id: pa.assembly.alleghenybeaverbutler.1805
  name: PA House of Representatives 1805, Allegheny, Beaver, and Butler Counties
- id: pa.assembly.armstrongindianajeffersonwestmoreland.1805
  name: PA House of Representatives 1805, Armstrong, Indiana, Jefferson, and Westmoreland Counties
- id: pa.assembly.bedford.1805
  name: PA House of Representatives 1805, Bedford County
- id: pa.assembly.berks.1805
  name: PA House of Representatives 1805, Berks County
- id: pa.assembly.bucks.1805
  name: PA House of Representatives 1805, Bucks County
- id: pa.assembly.chester.1805
  name: PA House of Representatives 1805, Chester County
- id: pa.assembly.crawforderiemercervenangowarren.1805
  name: PA House of Representatives 1805, Crawford, Erie, Mercer, Venango, and Warren Counties
- id: pa.assembly.cumberland.1805
  name: PA House of Representatives 1805, Cumberland County
- id: pa.assembly.dauphin.1805
  name: PA House of Representatives 1805, Dauphin County
- id: pa.assembly.delaware.1805
  name: PA House of Representatives 1805, Delaware County
- id: pa.assembly.fayette.1805
  name: PA House of Representatives 1805, Fayette County
- id: pa.assembly.franklin.1805
  name: PA House of Representatives 1805, Franklin County 
- pa.assembly.greene.1805
  name: PA House of Representatives 1805, Greene County
- id: pa.assembly.huntingdon.1805
  name: PA House of Representatives 1805, Huntingdon County
- id: pa.assembly.lancaster.1805
  name: PA House of Representatives 1805, Lancaster County
- id: pa.assembly.luzerne.1805
  name: PA House of Representatives 1805, Luzerne County
- id: pa.assembly.lycoming.1805
  name: PA House of Representatives 1805, Lycoming County
- id: pa.assembly.mifflin.1805
  name: PA House of Representatives 1805, Mifflin County
- id: pa.assembly.montgomery.1805
  name: PA House of Representatives 1805, Montgomery County
- id: pa.assembly.northamptonwayne.1805
  name: PA House of Representatives 1805, Northamption and Wayne Counties
- id: pa.assembly.northumberland.1805
  name: PA House of Representatives 1805, Northumberland County
- id: pa.assembly.philadelphia.1805
  name: PA House of Representatives 1805, Philadelphia County
- id: pa.assembly.philadelphiacity.1805
  name: PA House of Representatives 1805, City of Philadelphia
- id: pa.assembly.somerset.1805
  name: PA House of Representatives 1805, Somerset County
- id: pa.assembly.tioga.1805
  name: PA House of Representatives 1805, Tioga County
- id: pa.assembly.washington.1805
  name: PA House of Representatives 1805, Washington County
- id: pa.assembly.york.1805
  name: PA House of Representatives 1805, York County
related-maps:
- id: meae.staterepresentative.1806.pa.county
  name: PA 1806 House of Representatives
  type: next
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.staterepresentative.1805.pa.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~repfac_percentage, ~federalist_vote, ~demrep_vote, ~repfac_vote,
    "Philadelphia", 39.9526, -75.1652, 0.170, 0.830, 1535, 7507)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data(election_date = "1805-10-01") %>%
  map_counties(height = "500px", cities = 0, congress = 9) %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)<br/>",
                                "Republican faction: ", repfac_percentage * 100,
                                 "% (", 
                                 prettyNum(repfac_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city) 
```

</div>

Map Text 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
