---
meae-id: meae.congressional.congress07.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 7
congressordinal: 7th
title: '7th Congress: Vermont 1800'
year: 1800
legend: fed-vs-rep
nnv:
- id: vt.uscongress.western.1800
  name: VT US Congress 1800 District 1
- id: vt.uscongress.eastern.2.1800
  name: VT US Congress 1800 District 2
related-maps:
- id: meae.congressional.congress06.vt.county
  name: VT 6th Congress
  type: previous
- id: meae.congressional.congress08.vt.county
  name: VT 8th Congress
  type: next
- id: meae.congressional.congress07.national.county
  name: National 7th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress07.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px", congress = 7)
```

</div>

Vermont sent one Federalist and one Democratic-Republican to the Seventh Congress.

Vermont used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
