---
meae-id: meae.congressional.congress12.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: Tennessee 1811'
year: 1811
legend: fed-vs-rep
nnv:
- id: tn.congress.1.1811
  name: TN US Congress 1811 District 1
- id: tn.congress.2.1811
  name: TN US Congress 1811 District 2
- id: tn.congress.3.1811
  name: TN US Congress 1811 District 3
related-maps:
- id: meae.congressional.congress11.tn.county
  name: TN 11th Congress
  type: previous
- id: meae.congressional.congress13.tn.county
  name: TN 13th Congress
  type: next
#- id: meae.congressional.congress12.national.district
#  name: National 12th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "tns_nca4",
         id != "tns_nca7") %>% 
  map_counties(height = "300px", congress = 12)
```

</div>

Tennessee elected three Democratic-Republicans to the Twelfth Congress.

The map for this election is incomplete due to the lack of returns at the county level.

Tennessee used the district system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
