---
meae-id: meae.congressional.congress14.national.county
type: congressional
level: national
geography: county
congressnum: 14
congressordinal: 14th
title: '14th Congress: National, 1814-1815'
year: 1814
legend: 'fed-vs-rep'
related-maps:
- id: meae.congressional.congress13.national.county
  name: National 13th Congress
  type: previous
- id: meae.congressional.congress15.national.county
  name: National 15th Congress
  type: next
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
map_id <- "meae.congressional.congress14.national.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_national_map_data() %>%
  filter(id != "gas_nca") %>% 
  filter(id != "ins_nca1",
         id != "ins_nca2",
         id != "ins_nca3") %>%
  filter(!is.na(state_abbr),
          cross_ref != "New to dataset") %>%
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage), 
          cnty_type == "Parish") %>%  
  filter(id != "ohs_nca4",
         id != "ohs_nca5") %>% 
  filter(id != "scs_nca5") %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage), 
          cnty_type == "District") %>%
  filter(id != "tns_nca4",
         id != "tns_nca7") %>%
  filter(id != "int",
         id != "uba") %>%
  filter(!str_detect(id, "als_"),
         !str_detect(id, "ars_"),      
         !str_detect(id, "ils_"),
         !str_detect(id, "mit_"),
         !str_detect(id, "mos_"),
         !str_detect(id, "mss_")) %>%
  map_national(congress = 14)
```

</div>

<div class="results-table">

</div>
