---
meae-id: meae.congressional.congress13.nj.county
type: congressional
level: state
state: New Jersey
geography: county
congressnum: 13
congressordinal: 13th
title: '13th Congress: New Jersey 1813'
year: 1813
legend: fed-vs-rep
nnv:
- id: nj.uscongress1.1813
  name: NJ US Congress 1813 District 1
- id: nj.uscongress2.1813
  name: NJ US Congress 1813 District 2
- id: nj.uscongress3.1813
  name: NJ US Congress 1813 District 3
related-maps:
- id: meae.congressional.congress12.nj.county
  name: NJ 12th Congress
  type: previous
- id: meae.congressional.congress14.nj.county
  name: NJ 14th Congress
  type: next
- id: meae.congressional.congress13.national.county
  name: National 13th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress13.nj.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "700px", congress = 13)
```

</div>

New Jersey elected four Federalists and two Democratic-Republicans to the Thirteenth Congress.

New Jersey switched to a district system for electing members to Congress. Each district elected two members. 

In 1814, a [special election](https://elections.lib.tufts.edu/catalog/tufts:nj.uscongress.special.1814) was held in which Thomas Bines was elected to replace Jacob Hufty, who had died. 
<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
