---
meae-id: meae.congressional.congress13.sc.county
type: congressional
level: state
state: South Carolina
geography: county
congressnum: 13
congressordinal: 13th
title: '13th Congress: South Carolina 1812'
year: 1812
legend: fed-vs-rep
nnv:
- id: sc.uscongress.charleston.1812
  name: SC US Congress 1812 District 1
- id: sc.uscongress.beaufort.1812
  name: SC US Congress 1812 District 2
- id: sc.uscongress.georgetown.1812
  name: SC US Congress 1812 District 3
- id: sc.uscongress.orangeburg.1812
  name: SC US Congress 1812 District 4
- id: sc.uscongress.newberry.1812
  name: SC US Congress 1812 District 5
- id: sc.uscongress.edgefield.1812
  name: SC US Congress 1812 District 6
- id: sc.uscongress.pendleton.1812
  name: SC US Congress 1812 District 7
- id: sc.uscongress.chester.1812
  name: SC US Congress 1812 District 8
- id: sc.uscongress.sumter.1812
  name: SC US Congress 1812 District 9
related-maps:
- id: meae.congressional.congress12.sc.county
  name: SC 12th Congress
  type: previous
- id: meae.congressional.congress14.sc.county
  name: SC 14th Congress
  type: next
- id: meae.congressional.congress13.national.county
  name: National 13th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress13.sc.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote, 
  "Charleston", 32.7765, -79.9311, 0.387, 0.613, 752, 1190)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage), 
          cnty_type == "District") %>%
    filter(id != "scs_nca5") %>% 
  map_counties(cities = FALSE, height = "600px") %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
               fillColor = mappingelections:::poli_chrome(cities),
               opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100,
                                 "% (", 
                                 prettyNum(federalist_vote, big.mark = ","),
                                 " votes)<br/>",
                                "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city)
```

</div>

South Carolina elected one Federalist and eight Democratic-Republicans to the Thirteenth Congress.

The map for this election is incomplete due to the lack of returns in many areas.

Following the 1810 Census, South Carolina gained one more seat in the House of Representatives.

South Carolina used a district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
