---
meae-id: meae.congressional.congress16.ma.county
type: congressional
level: state
state: Massachusetts
geography: county
congressnum: 16
congressordinal: 16th
title: '16th Congress: Massachusetts 1818'
year: 1818
legend: fed-vs-rep
nnv:
- id: ma.uscongress.suffolk.1818
  name: MA US Congress 1818 District 1
- id: ma.uscongress.essexsouth.1818
  name: MA US Congress 1818 District 2
- id: ma.uscongress.essexnorth.1818
  name: MA US Congress 1818 District 3
- id: ma.uscongress.middlesex.1818
  name: MA US Congress 1818 District 4
- id: ma.uscongress.hampshiresouth.ballot2.1819
  name: MA US Congress 1819 District 5
- id: ma.uscongress.hampshirenorth.1818
  name: MA US Congress 1818 District 6
- id: ma.uscongress.berkshire.ballot2.1819
  name: MA US Congress 1819 District 7
- id: ma.uscongress.plymouth.1818
  name: MA US Congress 1818 District 8
- id: ma.uscongress.barnstable.1818
  name: MA US Congress 1818 District 9
- id: ma.uscongress.bristol.1818
  name: MA US Congress 1818 District 10
- id: ma.uscongress.worcestersouth.1818
  name: MA US Congress 1818 District 11
- id: ma.uscongress.worcesternorth.1818
  name: MA US Congress 1818 District 12
- id: ma.uscongress.norfolk.1818
  name: MA US Congress 1818 District 13
- id: ma.uscongress.eastern1.1818
  name: MA US Congress 1818 District 14
- id: ma.uscongress.eastern2.1818
  name: MA US Congress 1818 District 15
- id: ma.uscongress.eastern3.ballot3.1819
  name: MA US Congress 1819 District 16
- id: ma.uscongress.eastern4.ballot3.1819
  name: MA US Congress 1819 District 17
- id: ma.uscongress.eastern5.ballot2.1819
  name: MA US Congress 1819 District 18
- id: ma.uscongress.eastern6.1818
  name: MA US Congress 1818 District 19
- id: ma.uscongress.eastern7.1818
  name: MA US Congress 1818 District 20
related-maps:
- id: meae.congressional.congress15.ma.county
  name: MA 15th Congress
  type: previous
- id: meae.congressional.congress17.ma.county
  name: MA 17th Congress
  type: next
#- id: meae.congressional.congress16.national.district
#  name: National 16th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress16.ma.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties() %>% 
  fitBounds(-73.508, 41.186, -69.861, 43.75)
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
