---
meae-id: meae.congressional.congress06.sc.county
type: congressional
level: state
state: South Carolina
geography: county
congressnum: 6
congressordinal: 6th
title: '6th Congress: South Carolina 1798'
year: 1798
legend: fed-vs-rep
nnv:
- id: sc.uscongress.charleston.1798
  name: SC US Congress 1798 District 1
- id: sc.uscongress.beaufort.1798
  name: SC US Congress 1798 District 2
- id: sc.uscongress.georgetown.1798
  name: SC US Congress 1798 District 3
- id: sc.uscongress.camden.1798
  name: SC US Congress 1798 District 4
- id: sc.uscongress.ninety-six.1798
  name: SC US Congress 1798 District 5
- id: sc.uscongress.washington.1798
  name: SC US Congress 1798 District 6
related-maps:
- id: meae.congressional.congress05.sc.county
  name: SC 5th Congress
  type: previous
- id: meae.congressional.congress07.sc.county
  name: SC 7th Congress
  type: next
- id: meae.congressional.congress06.national.county
  name: National 6th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress06.sc.county"
cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~federalist_vote,
  "Charleston", 32.7765, -79.9311, 1.0, 863)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "scs_nca5") %>% 
  arrange(!is.na(federalist_percentage), !is.na(demrep_percentage)) %>% 
  map_counties(cities = FALSE, height = "600px", congress = 6) %>% 
   addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Federalists: ", federalist_percentage * 100, "% (", 
                                 prettyNum(federalist_vote, big.mark = ","), 
                                 " votes)"),
                 label = ~city) 
```

</div>

South Carolina elected five Federalists and one Democratic-Republican to the Sixth Congress.

The map for this election is incomplete due to the lack of returns at the parish or district level.

South Carolina used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
