---
meae-id: meae.congressional.congress03.ct.county
type: congressional
level: state
state: Connecticut
geography: county
congressnum: 3
congressordinal: 3rd
title: '3rd Congress: Connecticut 1792'
year: 1792
legend: fed-vs-anti
nnv:
- id: ct.congress.1792
  name: CT US Congress 1792 At Large
related-maps:
- id: meae.congressional.congress02.ct.county
  name: CT 2nd Congress
  type: previous
- id: meae.congressional.congress04.ct.county
  name: CT 4th Congress
  type: next
- id: meae.congressional.congress03.national.county
  name: National 3rd Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress03.ct.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "cts_wr") %>% 
  map_counties(height = "350px", congress = 3)
```

</div>

Connecticut elected seven Federalists to the Third Congress. 

Mapping this election is not possible because there are insufficient returns at the town and county levels.

Connecticut used a state-wide at-large system for electing members to Congress.

Several of Connecticut’s Congressmen were replaced in two different special elections in [May](https://elections.lib.tufts.edu/catalog/tufts:ct.special.congress.1793) and [December](https://elections.lib.tufts.edu/catalog/tufts:ct.special2.congress.1793) 1793.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
