---
meae-id: meae.congressional.congress11.ct.county
type: congressional
level: state
state: Connecticut
geography: county
congressnum: 11
congressordinal: 11th
title: '11th Congress: Connecticut 1808'
year: 1808
legend: dissrep
nnv:
- id: ct.congress.1808
  name: CT US Congress 1808 At Large
related-maps:
- id: meae.congressional.congress10.ct.county
  name: CT 10th Congress
  type: previous
- id: meae.congressional.congress12.ct.county
  name: CT 12th Congress
  type: next
- id: meae.congressional.congress11.national.district
  name: National 11th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress11.ct.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "350px", congress = 11)
```

</div>
Connecticut elected seven Federalists to the Eleventh Congress.

Mapping this election is not possible because of the lack of returns at the town or county level.

Connecticut used a statewide at-large method for electing members to Congress.
<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
