---
meae-id: meae.congressional.congress06.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 6
congressordinal: 6th
title: '6th Congress: Vermont 1798'
year: 1798
legend: fed-vs-rep
nnv:
- id: vt.uscongress.runoff.western.1798
  name: VT US Congress 1798 District 1
- id: vt.uscongress.eastern.1798
  name: VT US Congress 1798 District 2
related-maps:
- id: meae.congressional.congress05.vt.county
  name: VT 5th Congress
  type: previous
- id: meae.congressional.congress07.vt.county
  name: VT 7th Congress
  type: next
# - id: meae.congressional.congress06.national.district
#   name: National 6th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress06.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px")
```

</div>

Vermont sent one Federalist and one Democratic-Republican to the Sixth Congress.

Mapping this election is incomplete because of the lack of returns at the town or county level in many areas.

Vermont used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
