---
meae-id: meae.congressional.congress15.ct.county
type: congressional
level: state
state: Connecticut
geography: county
congressnum: 15
congressordinal: 15th
title: '15th Congress: Connecticut 1816'
year: 1816
legend: fed-vs-rep
nnv:
- id: ct.congress.1816
  name: CT US Congress 1816 At Large
related-maps:
- id: meae.congressional.congress14.ct.county
  name: CT 14th Congress
  type: previous
- id: meae.congressional.congress16.ct.county
  name: CT 16th Congress
  type: next
#- id: meae.congressional.congress15.national.district
#  name: National 15th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress15.ct.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "350px", congress = 15)
```

</div>

Connecticut elected seven Federalists to the Fifteenth Congress. Sylvanus Backus received support from both parties.

Mapping this election is not possible because of the lack of returns at the town or county level.

Connecticut used a statewide at-large system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
