---
meae-id: meae.congressional.congress05.vt.county
type: congressional
level: state
state: Vermont
geography: county
congressnum: 5
congressordinal: 5th
title: '5th Congress: Vermont 1796'
year: 1796
legend: fed-vs-rep
nnv:
- id: vt.uscongress.western.thirdballot.1797
  name: VT US Congress 1797 District 1
- id: vt.uscongress.eastern.1796
  name: VT US Congress 1796 District 2
related-maps:
- id: meae.congressional.congress04.vt.county
  name: VT 4th Congress
  type: previous
- id: meae.congressional.congress06.vt.county
  name: VT 6th Congress
  type: next
- id: meae.congressional.congress05.national.county
  name: National 5th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress05.vt.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "600px")
```

</div>

Vermont sent one Federalist and one Democratic-Republican to the Fifth Congress.

The map for this election is incomplete due to the lack of returns at the county level.

Vermont used the district system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
