---
meae-id: meae.congressional.congress01.ny.county
type: congressional
level: state
state: New York
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: New York 1789'
year: 1789
legend_type: fed-vs-repub-percentage
nnv:
- id: ny.uscongress1.1789
  name: NY US Congress 1789 District 1
- id: ny.uscongress2.1789
  name: NY US Congress 1789 District 2
- id: ny.uscongress3.1789
  name: NY US Congress 1789 District 3
- id: ny.uscongress4.1789
  name: NY US Congress 1789 District 4
- id: ny.uscongress5.1789
  name: NY US Congress 1789 District 5
- id: ny.uscongress6.1789
  name: NY US Congress 1789 District 6
related-maps:
- id: meae.congressional.congress02.ny.county
  name: NY Second Congress
  type: next
- id: meae.congressional.congress01.national.district
  name: National First Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress01.ny.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>% 
  get_county_map_data() %>% 
  map_counties(height = "550px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>% 
  candidate_results() %>% 
  results_to_table() %>% 
  cat()
```

</div>
