---
meae-id: meae.congressional.congress19.md.county
type: congressional
level: state
state: Maryland
geography: county
congressnum: 19
congressordinal: 19th
title: '19th Congress: Maryland 1824'
year: 1824
legend: fed-vs-rep
nnv:
- id: md.uscongress1.1824
  name: MD US Congress 1824 District 1
- id: md.uscongress2.1824
  name: MD US Congress 1824 District 2
- id: md.uscongress3.1824
  name: MD US Congress 1824 District 3
- id: md.uscongress4.1824
  name: MD US Congress 1824 District 4
- id: md.uscongress5.1824
  name: MD US Congress 1824 District 5
- id: md.uscongress6.1824
  name: MD US Congress 1824 District 6
- id: md.uscongress7.1824
  name: MD US Congress 1824 District 7
- id: md.uscongress8.1824
  name: MD US Congress 1824 District 8
related-maps:
- id: meae.congressional.congress18.md.county
  name: MD 18th Congress
  type: previous
#- id: meae.congressional.congress19.national.district
#  name: National 19th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress19.md.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~demrep_percentage, ~demrep_vote,
  "Baltimore", 39.30021, -76.61052, 1.0, 13215)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px", cities = FALSE) %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city)

```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
