---
meae-id: meae.congressional.congress06.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 6
congressordinal: 6th
title: '6th Congress: Tennessee 1799'
year: 1799
legend: fed-vs-rep
nnv:
- id: tn.congress.1799
  name: TN US Congress 1799 At Large
related-maps:
- id: meae.congressional.congress05.tn.county
  name: TN 5th Congress
  type: previous
- id: meae.congressional.congress07.tn.county
  name: TN 7th Congress
  type: next
# - id: meae.congressional.congress06.national.district
#   name: National 6th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress06.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "tns_nca1",
         id != "tns_nca2") %>% 
  map_counties(height = "300px")
```

</div>

Tennessee elected one Democratic-Republican to the Sixth Congress.

Mapping this election is incomplete because of the lack of returns at the town or county level in many areas.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
