---
meae-id: meae.congressional.congress18.in.county
type: congressional
level: state
state: Indiana
geography: county
congressnum: 18
congressordinal: 18th
title: '18th Congress: Indiana 1822'
year: 1822
legend: congress-18-19
nnv:
- id: in.usrepresentative.1st.1822
  name: IN US Congress 1822 District 1
- id: in.usrepresentative.2nd.1822
  name: IN US Congress 1822 District 2
- id: in.usrepresentative.3rd.1822
  name: IN US Congress 1822 District 3
related-maps:
- id: meae.congressional.congress17.in.county
  name: IN 17th Congress
  type: previous
- id: meae.congressional.congress19.in.county
  name: IN 19th Congress
  type: next
#- id: meae.congressional.congress18.national.district
# name: National 18th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress18.in.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  filter(id != "ins_nca4",
         id != "ins_nca6") %>%
  map_counties(height = "775px")
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
