---
meae-id: meae.congressional.congress15.md.county
type: congressional
level: state
state: Maryland
geography: county
congressnum: 15
congressordinal: 15th
title: '15th Congress: Maryland 1816'
year: 1816
legend: fed-vs-rep
nnv:
- id: md.uscongress1.1816
  name: MD US Congress 1816 District 1
- id: md.uscongress2.1816
  name: MD US Congress 1816 District 2
- id: md.uscongress3.1816
  name: MD US Congress 1816 District 3
- id: md.uscongress4.1816
  name: MD US Congress 1816 District 4
- id: md.uscongress5.1816
  name: MD US Congress 1816 District 5
- id: md.uscongress6.1816
  name: MD US Congress 1816 District 6
- id: md.uscongress7.1816
  name: MD US Congress 1816 District 7
- id: md.uscongress8.1816
  name: MD US Congress 1816 District 8
related-maps:
- id: meae.congressional.congress14.md.county
  name: MD 14th Congress
  type: previous
- id: meae.congressional.congress16.md.county
  name: MD 16th Congress
  type: next
#- id: meae.congressional.congress15.national.district
#  name: National 15th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress15.md.county"

cities <- tribble(
  ~city, ~lat, ~lng, ~demrep_percentage, ~demrep_vote,
  "Baltimore", 39.30021, -76.61052, 1.0, 7757)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "450px", cities = FALSE) %>%
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                 fillColor = mappingelections:::poli_chrome(cities),
                 opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                 popup = ~paste0("<b>City of ", city, "</b><br/>",
                                 "Congressional District: 1<br/>",
                                 "Democratic-Republicans: ", demrep_percentage * 100,
                                 "% (", 
                                 prettyNum(demrep_vote, big.mark = ","),
                                 " votes)"),
                 label = ~city)
```

</div>

Maryland elected five Federalists and four Democratic-Republicans to the Fifteenth Congress. 

Maryland used a district system for electing members to Congress. District 5 elected two members.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
