---
meae-id: meae.congressional.congress19.mo.county
type: congressional
level: state
state: Missouri
geography: county
congressnum: 19
congressordinal: 19th
title: '19th Congress: Missouri 1824'
year: 1824
legend: congress-18-19
nnv:
- id: mo.uscongress.1824
  name: MO US Congress 1824 At Large
related-maps:
- id: meae.congressional.congress18.mo.county
  name: MO 18th Congress
  type: previous
#- id: meae.congressional.congress19.national.district
#  name: National 19th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress19.mo.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "mos_nca1",
         id != "mos_nca3",
         id != "mos_nca4",
         id != "mos_nca6",
         id != "mos_nca7",
         id != "mos_nca8",
         id != "mos_nca9",
         id != "mos_nca10") %>% 
  map_counties(height = "650px")
```

</div>

Missouri elected one Democratic-Republican to the Nineteenth Congress. The Democratic-Republican was part of a faction led by John Quincy Adams and Henry Clay.

The map for this election is incomplete due to the lack of returns at the town or county level.

Missouri used a statewide at-large system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
