---
meae-id: meae.congressional.congress15.nj.county
type: congressional
level: state
state: New Jersey
geography: county
congressnum: 15
congressordinal: 15th
title: '15th Congress: New Jersey 1816'
year: 1816
legend: fed-vs-rep
nnv:
- id: nj.uscongress.1816
  name: NJ US Congress 1816 At Large
related-maps:
- id: meae.congressional.congress14.nj.county
  name: NJ 14th Congress
  type: previous
- id: meae.congressional.congress16.nj.county
  name: NJ 16th Congress
  type: next
- id: meae.congressional.congress15.national.county
  name: National 15th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress15.nj.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "700px", congress = 15)
```

</div>

New Jersey elected six Democratic-Republicans to the Fifteenth Congress.

The map for this election is incomplete due to the lack of returns at the town or county level.

New Jersey used a statewide at-large system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
