---
meae-id: meae.congressional.congress10.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 10
congressordinal: 10th
title: '10th Congress: Tennessee 1807'
year: 1807
legend: fed-vs-rep
nnv:
- id: tn.congress.washington.1807
  name: TN US Congress 1807 District 1
- id: tn.congress.hamilton.1807
  name: TN US Congress 1807 District 2
- id: tn.congress.mero.1807
  name: TN US Congress 1807 District 3
related-maps:
- id: meae.congressional.congress09.tn.county
  name: TN 9th Congress
  type: previous
- id: meae.congressional.congress11.tn.county
  name: TN 11th Congress
  type: next
# - id: meae.congressional.congress10.national.district
#   name: National 10th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress10.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  filter(id != "tns_nca3",
         id != "tns_nca4") %>% 
  map_counties(height = "300px", congress = 10)
```

</div>

Tennessee elected three Democratic-Republicans to the Tenth Congress.

Mapping this election is incomplete because of the lack of local returns in many areas.

Tennessee used the district system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
