---
meae-id: meae.congressional.congress01.nh.county
type: congressional
level: state
state: New Hampshire
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: New Hampshire 1789'
year: 1789
nnv:
- id: nh.uscongress.1789
  name: NH US Congress 1789 At Large
related-maps:
- id: meae.congressional.congress02.nh.county
  name: NH 2nd Congress
  type: next
- id: meae.congressional.congress01.national.district
  name: National 1st Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress01.nh.county"
```

NNV contains town- or county-level returns for less than 20 percent of the total votes cast in this election, so the data cannot be meaningfully mapped. The overall results of the elections are listed below.

Though Benjamin West received the most votes for the House of Representatives, he declined the election and Abiel Foster served as representative instead.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table(keep_percentage = 0.01) %>%
  cat()
```

</div>
