---
meae-id: meae.congressional.congress12.de.county
type: congressional
level: state
state: Delaware
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: Delaware 1810'
year: 1810
legend: fed-vs-rep
nnv:
- id: de.uscongress.1810
  name: DE US Congress 1810 At Large
related-maps:
- id: meae.congressional.congress11.de.county
  name: DE 11th Congress
  type: previous
- id: meae.congressional.congress13.de.county
  name: DE 13th Congress
  type: next
#- id: meae.congressional.congress12.national.district
#  name: National 12th Congress
#  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.de.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data()  %>%
  map_counties(height = "450px")
```

</div>

Delaware elected one Federalist to the Twelfth Congress.

Delaware used a statewide at-large method for electing members to Congress. Delaware’s election law required that voters select two candidates, with one residing in the voter’s own county, and the other residing in one of the state's other two counties. The at-large winner was elected.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
