---
meae-id: meae.congressional.congress07.tn.county
type: congressional
level: state
state: Tennessee
geography: county
congressnum: 7
congressordinal: 7th
title: '7th Congress: Tennessee 1801'
year: 1801
legend: fed-vs-rep
nnv:
- id: tn.congress.1801
  name: TN US Congress 1801 At Large
related-maps:
- id: meae.congressional.congress06.tn.county
  name: TN 6th Congress
  type: previous
- id: meae.congressional.congress08.tn.county
  name: TN 8th Congress
  type: next
- id: meae.congressional.congress07.national.county
  name: National 7th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress07.tn.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "tns_nca1",
         id != "tns_nca2") %>% 
  map_counties(height = "300px")
```

</div>

Tennessee elected one Democratic-Republican to the Seventh Congress.

Mapping this election is not possible because of the lack of returns at the town or county level.

In November 1801, a [special election](https://elections.lib.tufts.edu/catalog/tufts:tn.ushouserepresentativespecial.1801) was held in which William Dickson was elected to replace William C. C. Claiborne, who was appointed Governor of Mississippi Territory.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
