---
meae-id: meae.congressional.congress08.nc.county
type: congressional
level: state
state: North Carolina
geography: county
congressnum: 8
congressordinal: 8th
title: '8th Congress: North Carolina 1803'
year: 1803
legend: fed-vs-rep
nnv:
- id: nc.uscongress1.1803
  name: NC US Congress 1803 District 1
- id: nc.uscongress2.1803
  name: NC US Congress 1803 District 2
- id: nc.uscongress3.1803
  name: NC US Congress 1803 District 3
- id: nc.uscongress4.1803
  name: NC US Congress 1803 District 4
- id: nc.uscongress5.1803
  name: NC US Congress 1803 District 5
- id: nc.uscongress6.1803
  name: NC US Congress 1803 District 6
- id: nc.uscongress7.1803
  name: NC US Congress 1803 District 7
- id: nc.uscongress8.1803
  name: NC US Congress 1803 District 8
- id: nc.uscongress9.1803
  name: NC US Congress 1803 District 9
- id: nc.uscongress10.1803
  name: NC US Congress 1803 District 10
- id: nc.uscongress11.1803
  name: NC US Congress 1803 District 11
- id: nc.uscongress12.1803
  name: NC US Congress 1803 District 12
related-maps:
- id: meae.congressional.congress07.nc.county
  name: NC 7th Congress
  type: previous
- id: meae.congressional.congress09.nc.county
  name: NC 9th Congress
  type: next
- id: meae.congressional.congress08.national.county
  name: National 8th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress08.nc.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", congress = 8)
```

</div>

North Carolina elected one Federalist and eleven Democratic-Republicans to the Eighth Congress.

Following the 1800 Census, North Carolina gained two seats in the House of Representatives.

North Carolina used the district system for electing members to Congress. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
