---
meae-id: meae.congressional.congress01.ct.county
type: congressional
level: state
state: Connecticut
geography: county
congressnum: 1
congressordinal: 1st
title: '1st Congress: Connecticut 1790'
year: 1790
legend: fed-vs-anti
nnv:
- id: ct.congress.1790
  name: CT US Congress 1790 At Large
related-maps:
- id: meae.congressional.congress02.ct.county
  name: CT 2nd Congress
  type: next
- id: meae.congressional.congress01.national.district
  name: National 1st Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show
---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress01.ct.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>% 
  filter(id != "cts_wr") %>%  # Remove the Western Reserve
  map_counties(height = "350px", congress = 1) #%>% 
  # setView(lng = -81.492, lat = 32.348, zoom = 7)
```

</div>

NNV does not contain any county- or town-level data to be mapped. Elections for Connecticut's five seats in the First Congress were held in a state-wide at-large election. Pierpont Edwards was elected, but he declined to serve and was replaced by Jeremiah Wadsworth in a [special election](http://elections.lib.tufts.edu/catalog/tufts:ct.special.congress.1790). 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
