---
meae-id: meae.congressional.congress12.nc.county
type: congressional
level: state
state: North Carolina
geography: county
congressnum: 12
congressordinal: 12th
title: '12th Congress: North Carolina 1810'
year: 1810
legend: fed-vs-rep
nnv:
- id: nc.uscongress1.1810
  name: NC US Congress 1810 District 1
- id: nc.uscongress2.1810
  name: NC US Congress 1810 District 2
- id: nc.uscongress3.1810
  name: NC US Congress 1810 District 3
- id: nc.uscongress4.1810
  name: NC US Congress 1810 District 4
- id: nc.uscongress5.1810
  name: NC US Congress 1810 District 5
- id: nc.uscongress6.1810
  name: NC US Congress 1810 District 6
- id: nc.uscongress7.1810
  name: NC US Congress 1810 District 7
- id: nc.uscongress8.1810
  name: NC US Congress 1810 District 8
- id: nc.uscongress9.1810
  name: NC US Congress 1810 District 9
- id: nc.uscongress10.1810
  name: NC US Congress 1810 District 10
- id: nc.uscongress11.1810
  name: NC US Congress 1810 District 11
- id: nc.uscongress12.1810
  name: NC US Congress 1810 District 12
related-maps:
- id: meae.congressional.congress11.nc.county
  name: NC 11th Congress
  type: previous
- id: meae.congressional.congress13.nc.county
  name: NC 13th Congress
  type: next
- id: meae.congressional.congress12.national.county
  name: National 12th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress12.nc.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "500px", congress = 12)
```

</div>

North Carolina elected two Federalists and ten Democratic-Republicans to the Twelfth Congress.

North Carolina used the district system for electing members to Congress.

In 1813, a [special election](https://elections.lib.tufts.edu/catalog/tufts:nc.uscongress3.specialelection.1813) was held in which William Kennedy was elected to replace Thomas Blount, who had died. 

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
