---
meae-id: meae.congressional.congress04.ga.county
type: congressional
level: state
state: Georgia
geography: county
congressnum: 4
congressordinal: 4th
title: '4th Congress: Georgia 1795'
year: 1795
legend: fed-vs-rep
nnv:
- id: ga.uscongress.1795
  name: GA US Congress 1795 At Large
related-maps:
- id: meae.congressional.congress03.ga.county
  name: GA 3rd Congress
  type: previous
- id: meae.congressional.congress05.ga.county
  name: GA 5th Congress
  type: next
# - id: meae.congressional.congress04.national.district
#   name: National 4th Congress
#   type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)
library(sf)

map_id <- "meae.congressional.congress04.ga.county"
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  filter(id != "gas_nca") %>% 
  map_counties(height = "500px") %>% 
  setView(lng = -81.492, lat = 32.348, zoom = 7)
```

</div>

Georgia elected two representatives not officially affiliated with any party to the Fourth Congress.

Georgia used a statewide at-large system for electing members to Congress.

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
