---
layout: map-show
...


```{r, include = FALSE}
library(tidyverse)
library(stringr)
library(htmlTable)
library(formattable)
```

```{r, echo = FALSE, message = FALSE}
md_raw <- read_csv("congressional-counties-md.csv")
table_data <- md_raw %>% 
  filter(str_detect(election_id, "1796")) %>% 
  group_by(candidate, election_id, party) %>% 
  summarize(vote = sum(vote, na.rm = TRUE)) %>% 
  group_by(election_id) %>% 
  mutate(total_vote = sum(vote)) %>% 
  mutate(percent_vote = vote / total_vote) %>% 
  mutate(district = str_extract(election_id, "\\d")) %>% 
  mutate(winner = vote == max(vote)) %>% 
  top_n(3, vote) %>% 
  arrange(district, desc(vote)) %>% 
  mutate(percent_display = str_c(round(percent_vote * 100, 1), "%")) %>% 
  mutate(won = if_else(winner, "won", "")) %>% 
  ungroup() %>% 
  select(district, candidate, party, vote, percent_display, won) %>% 
  filter(vote > 20)

districts <- paste("District ", table_data$district %>% unique())

ngroup <- table_data$district %>% table() %>% as.integer()

test <- htmlTable(select(table_data, -district), rgroup = districts, n.rgroup = ngroup, rnames = FALSE)
test

help(package="formattable")

formattable(table_data,
            list(district = formatter("tr", style = x ~ ifelse(as.integer(x) %% 2 == 0, "color:red", "color:green"))))

area(col = c("mpg", "cyl"))

format_table(mtcars, list(area(col = vs:carb) ~ formatter("span",
  style = x ~ style(color = ifelse(x > 0, "red", NA)))))

vignette("introduction", package="formattable")

```


