---
meae-id: meae.congressional.congress08.md.county
type: congressional
level: state
state: Maryland
geography: county
congressnum: 8
congressordinal: 8th
title: '8th Congress: Maryland 1803'
year: 1803
legend: fed-vs-rep
nnv:
- id: md.uscongress1.1803
  name: MD US Congress 1803 District 1
- id: md.uscongress2.1803
  name: MD US Congress 1803 District 2
- id: md.uscongress3.1803
  name: MD US Congress 1803 District 3
- id: md.uscongress4.1803
  name: MD US Congress 1803 District 4
- id: md.uscongress5.1803
  name: MD US Congress 1803 District 5
- id: md.uscongress6.1803
  name: MD US Congress 1803 District 6
- id: md.uscongress7.1803
  name: MD US Congress 1803 District 7
- id: md.uscongress8.1803
  name: MD US Congress 1803 District 8
related-maps:
- id: meae.congressional.congress07.md.county
  name: MD 7th Congress
  type: previous
- id: meae.congressional.congress09.md.county
  name: MD 9th Congress
  type: next
- id: meae.congressional.congress08.national.district
  name: National 8th Congress
  type: national
output:
  md_document:
    variant: markdown
  html_document:
    theme: default
always_allow_html: yes
layout: maps-show

---

```{r setup, include = FALSE}
library(leaflet)
library(tidyverse)
library(USAboundaries)
library(mappingelections)

map_id <- "meae.congressional.congress08.md.county"
cities <- tribble(
  ~city, ~lat, ~lng, ~federalist_percentage, ~demrep_percentage, ~federalist_vote, ~demrep_vote,
  "Baltimore", 39.30021, -76.61052, 0.045, 0.955, 208, 4385 
)
```

<div class="map">

```{r election-map, echo = FALSE}
map_id %>%
  get_county_map_data() %>%
  map_counties(height = "425px", cities = FALSE) %>% 
  addCircleMarkers(data = cities, lat = ~lat, lng = ~lng, color = "black",
                   fillColor = mappingelections:::poli_chrome(cities),
                   opacity = 1, fillOpacity = 0.8, radius = 8, weight = 3,
                   popup = ~paste0("<b>City of ", city, "</b><br/>",
                                   "Congressional District: At-large<br/>",
                                   "Federalists: ", federalist_percentage * 100, "% (", 
                                   prettyNum(federalist_vote, big.mark = ","), 
                                   " votes)<br/>",
                                   "Democratic-Republicans: ", demrep_percentage * 100,
                                   "% (", 
                                   prettyNum(demrep_vote, big.mark = ","),
                                   " votes)"),
                   label = ~city) 
```

</div>

<div class="results-table">

```{r election-results, echo = FALSE, results='asis'}
map_id %>%
  candidate_results() %>%
  results_to_table() %>%
  cat()
```

</div>
